function set_enable_loop(enable_loop)
    error_code = ...
        cepton_sdk.c.call( ...
            'cepton_sdk_capture_replay_set_enable_loop', enable_loop);
    cepton_sdk.c.check_error_code(error_code);
end
