macro(PARSE_VERSION_STRING PREFIX)
  string(REPLACE "."
                 ";"
                 ${PREFIX}_VERSION_LIST
                 "${${PREFIX}_VERSION}")
  list(LENGTH ${PREFIX}_VERSION_LIST ${PREFIX}_VERSION_LIST_SIZE)
  set(${PREFIX}_VERSION_MAJOR 0)
  set(${PREFIX}_VERSION_MINOR 0)
  set(${PREFIX}_VERSION_PATCH 0)
  if(${PREFIX}_VERSION_LIST_SIZE GREATER 0)
    list(GET ${PREFIX}_VERSION_LIST 0 ${PREFIX}_VERSION_MAJOR)
  endif()
  if(${PREFIX}_VERSION_LIST_SIZE GREATER 1)
    list(GET ${PREFIX}_VERSION_LIST 1 ${PREFIX}_VERSION_MINOR)
  endif()
  if(${PREFIX}_VERSION_LIST_SIZE GREATER 2)
    list(GET ${PREFIX}_VERSION_LIST 2 ${PREFIX}_VERSION_PATCH)
  endif()
endmacro()

macro(PARSE_VERSION_FILE VERSION_PATH PREFIX)
  file(READ "${VERSION_PATH}" ${PREFIX}_VERSION)
  string(STRIP "${${PREFIX}_VERSION}" ${PREFIX}_VERSION)
  parse_version_string(${PREFIX})
endmacro()

parse_version_file("${CMAKE_CURRENT_LIST_DIR}/../VERSION" CEPTON)
