if(WIN32)
  set(OS_NAME "win64")
elseif(APPLE)
  set(OS_NAME "osx")
elseif(UNIX)
  execute_process(COMMAND uname -m OUTPUT_VARIABLE MACHINE_ARCH OUTPUT_STRIP_TRAILING_WHITESPACE)
  set(OS_NAME "linux-${MACHINE_ARCH}")
else()
  message(FATAL_ERROR "unsupported architecture")
endif()